<!DOCTYPE html>
	<head>
		<html lang="en">
		<meta charset="UTF-8">
		<title>Verschlüsselung | Wichtl Verlosung 2024</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">

		<!-- CSS Stylesheets -->
		<link rel="stylesheet" href="https://unpkg.com/primitive-ui/dist/css/main.css" />
		<link rel="stylesheet" href="style.css?v=1.0">
	</head>

	<body>
		<main class="container small-container">

			<div class="content-section">
				<h1>🎅🏻 Wichtl Verlosung 2024</h1>

				<div id="names">
					<!-- markup generated by JS -->
				</div>
			</div>

		</main>
	</body>

	<footer>

	</footer>
		
	<!-- JS Scripts -->
	<script src="functions.js?v=1.0"></script>
	<script>

let assignments = assignNames( people );
while ( !checkAssignments( assignments ) ) {
	assignments = assignNames( people );
}

// success!
console.log( "Everything worked fine! Final assignments:", assignments );

// encrypt
const encryptedAssignments = encryptAssignments( assignments );

// create table
createTable( 'names', encryptedAssignments );
console.log( encryptedAssignments );

	</script>
</html>
